name: SonarQube Quality Gate
on:
  workflow_run:
    workflows: ["Build and Test"]
    types:
      - completed

jobs:
  quality_gate:
    name: SonarQube Cloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Download Coverage Report
        uses: actions/download-artifact@v4
        with:
          name: coverage-report
          path: reports/
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Verify Coverage Report Exists
        run: ls -l reports/
      - name: SonarQube Cloud Scan
        uses: sonarsource/sonarqube-scan-action@v4.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: -Dsonar.python.coverage.reportPaths=reports/coverage.xml
      - name: Update Status in GitHub
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { context } = require('@actions/github');
            const status = context.payload.workflow_run.conclusion === 'success' ? 'success' : 'failure';
            await github.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.payload.workflow_run.head_commit.id,
              state: status,
              context: 'SonarQube Quality Gate',
              description: 'SonarQube Quality Gate Check',
              target_url: context.run.html_url
            });
